#ifndef READ_ENUM_H
#define READ_ENUM_H

enum read_status {
    READ_OK = 0,
    READ_INVALID_HEADER,
    READ_INVALID_BITS,
    READ_EMPTY_FILE,
    READ_INVALID_TYPE,
    READ_INVALID_FILESIZE,
    READ_INVALID_RESERVED,
    READ_INVALID_PLANES,
    READ_INVALID_SIZE,
    READ_INVALID_BITS_COUNT,
    READ_INVALID_WIDTH,
    READ_INVALID_HEIGTH,
    READ_INVALID_OFFBITS
};

#endif
